### ISSUE TITLE
Request: Test data

### ISSUE THREAD

**Issue by vdun** [libyal/libvshadow#22]
A tiny ntfs image file with VSS for testing.

**Comment by joachimmetz** [comment]
@vdun it is unclear what you are requesting

**Comment by joachimmetz** [comment]
@vdun here are some scripts to create one yourself https://github.com/dfirlabs/vss-specimens, note that there are minimum image size requirements.

**Comment by vdun** [comment]
Thx.
Is there an already generated one ready for direct download ?

**Comment by joachimmetz** [comment]
I cannot give you much advice here, since you've not indicated what you are planning to test.

No, from https://github.com/libyal/libvshadow/wiki/Testing#test-files
`Note that no test files are provided by the project.`

There is a test image in dfVFS and plaso https://github.com/log2timeline/dfvfs/blob/master/test_data/vsstest.qcow2 but that is a QCOW2 image but that is not suitable for testing libvshadow directly.
